version: 0.1
phases:
  install:
    commands:
      - sudo npm install
      - sudo npm install --only=dev
  build:
    commands:
      - sudo ./node_modules/react-scripts/bin/react-scripts.js build
  post_build:
    commands:
      - aws s3 sync --delete --exclude static/* build/ "s3://${BUCKET_NAME}"
