version: 0.1
phases:
  build:
    commands:
      - aws s3 sync --delete --exclude static/* * "s3://${BUCKET_NAME}"
      - aws s3 sync --delete --cache-control "max-age=31536000" static "s3://${BUCKET_NAME}/static"
